# Generated by Django 4.2.6 on 2023-10-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniverstiyClasses',
            new_name='UniversityClasses',
        ),
    ]
